### ISSUE TITLE
Combine schemas with same securityDefinition fails

### ISSUE THREAD

**Issue by nexinto-gmbh** [maxdome/swagger-combine#10]
Hi,

if two schemas uses the same securityDefintions, the combineSchema function throws a conflict error, because the securityKeys will be checked instead of there definition. A simple deepCompare will fix the problem.

```
// Outline securityDefinitions
const securityDefinitions = _.get(schema, 'securityDefinitions')
const conflictingSecurityDefs = _.intersection(
  _.keys(this.combinedSchema.securityDefinitions),
  _.keys(securityDefinitions),
)
// and filter identical definitions
.filter(key => !_.isEqual(securityDefinitions[key], this.combinedSchema.securityDefinitions[key]))
```

It would be nice to see this or an other solution in one of the next releases.

Thx

**Comment by fabsrc** [comment]
Hi, thanks for reporting this bug and for your proposed solution.

This seems like a quick fix. I think we can implement it soon, but if you want to, you can also implement it yourself (including tests and README adjustments) and make a pull request.

A solution that works without this fix would be to use the `renameSecurityDefinitions` functionality by adding this to your config: 
```json
{
  "apis": [
    {
      "securityDefinitions": {
        "rename": {
          "auth_to_rename": "renamed_auth"
        }
      }
    }
  ]
}
```

In the future it would also be nice to have a feature that resolves duplicated securityDefinition names by renaming them automatically, but we will look into that at another time.

**Comment by nexinto-gmbh** [comment]
The problem here is, that I don't want to rename anything, because the securityDefinition are the same and should be merged if they are identical.
The posibility to rename a securityDefinition is another option and is independent of the merge. 

In my case, I've different schemas with the same securityDefinition and want to combine them, without doublicating the securityDefinitions.

But I think the real problem is: How to combine global (path independend) and local (path dependen) securityDefinition. I think, the securityDefinition must also be **dereferenced** and set explicit for every path.

**Comment by fabsrc** [comment]
Dereferencing the security definitions would solve the problem, but as far as I know this is not possible with the Swagger spec (at least not with version 2.0). 
The `securityDefinitions` have to be declared globally ([see Swagger 2.0 Spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields)). The `security` requirements can be defined locally, but still need to reference the `securityDefinitions`.

**Comment by nexinto-gmbh** [comment]
#12
