### ISSUE TITLE
Question: How would you calculate the combined version number/string?

### ISSUE THREAD

**Issue by nexinto-gmbh** [maxdome/swagger-combine#14]
Hi again,

I would prefere a method to calculate the combined version number based on every single schema version number.
Based on the swagger definition a version is a string. It does not have to be a string like major.minor.patch which can be splited and accumulated by default.

So I think its necessary to configure a callback on swaggerCombine / middleware, where the calculation can be done.
At the moment the only way to configure the behavior is to define a config.json. But the necessary functional part is missing.

I hope you have an idea or will accept such a solution, so I can create a pull request.

Thx

**Comment by fabsrc** [comment]
I'm not sure if this is a feature that would be used frequently, so I'm not fully convinced to include it in this module.

You could easily achieve this by using the `SwaggerCombine` class directly.
Here is an example how to do this:

```js
const sc = require('swagger-combine');

const config = {
  swagger: '2.0',
  info: {
    title: 'Basic Swagger Combine Example',
    version: ''
  },
  apis: [
    {
      url: 'http://petstore.swagger.io/v2/swagger.json',
    },
    {
      url: 'https://api.apis.guru/v2/specs/medium.com/1.0.0/swagger.yaml',
    },
    {
      url: 'https://api.apis.guru/v2/specs/deutschebahn.com/betriebsstellen/v1/swagger.json',
    },
  ],
};

new sc.SwaggerCombine(config)
  .combine()
  .then(res => {
    res.combinedSchema.info.version = res.schemas
      .reduce((version, schema) => version + `[${schema.info.title} - ${schema.info.version}] `, '')
      .trim();
    return res.combinedSchema;
  })
  .then(res => console.log(res.info))
  .catch(e => console.error(e));
```

**Comment by nexinto-gmbh** [comment]
Thx,
thats the correct approach.

```
const json = await new sc.SwaggerCombine(config)
      .combine()
      .then(res => {
        res.combinedSchema.info.version = res.schemas
          .reduce((version, schema) => {
            const [minor = '1', major = '0', patch = '0'] = schema.info.version.split('.')
            version[0] += Number.parseInt(minor, 10)
            version[1] += Number.parseInt(major, 10)
            version[2] += Number.parseInt(patch.split('-')[0], 10)
            return version
          }, [0, 0, 0]).join('.')
        return res.combinedSchema
      })
```
