### ISSUE TITLE
Document how to select the output format and support the choice on the command line

### ISSUE THREAD

**Issue by odupuy** [maxdome/swagger-combine#33]
I naively thought that by using a YAML configuration file and even a yaml output that you would get a yaml file e.g. `./node_modules/swagger-combine/bin/swagger-combine docs/swagger.yaml -o api.yaml` but this is not the case. The output is Json.

Is there a way on the command line or in configuration file to specify the type of output?
If not can you add this, this would be handy.

I ended up running `node middleware.js` with this one being [this](https://github.com/maxdome/swagger-combine#middleware) then `wget http://localhost:3333/swagger.yaml` but if there can be a simpler solution then all the better.

Thanks

**Comment by fabsrc** [comment]
The output format is not configurable at this point, so it is always JSON. Thanks for pointing this out. We will add an option to specify the output format.
