### ISSUE TITLE
continueOnError causes failure during addBasePath

### ISSUE THREAD

**Issue by maritz** [maxdome/swagger-combine#43]
When continueOnError is set to true and the api option that is failing includes a paths option, an error is thrown and no json produced.

This is not covered by the [test here](https://github.com/maxdome/swagger-combine/blob/93f73eff125865fc594d9f9b7e178e9f289cb004/test/integration.spec.js#L46) because it only tests a failing api that has no further options set. Thus none of the later steps try to access the undefined schema.

I didn't go through the entire code, but I'd suspect that the same happens with other things, not just basePath.

My proposal would be to discard all failed apis when continueOnError is true.

Something like this [here](https://github.com/maxdome/swagger-combine/blob/v0.16.1/src/SwaggerCombine.js#L72):

```javascript
if (this.opts.continueOnError) {
  apis = apis.filter((api) => api !== undefined);
}
```

Alternatively checking in each further step whether schema is undefined in the schema.map() is also an option.

Here's a failing integration test:

```javascript
  it('catches errors if `continueOnError` option is set to true and a swagger config is unreachable for extended api config', () => {
    nock('https://api.apis.guru')
      .get('/v2/specs/deutschebahn.com/betriebsstellen/v1/swagger.json')
      .reply(500);

    return swaggerCombine(basicConfig, { continueOnError: true });
  });
```

**Comment by fabsrc** [comment]
Thank you for finding and reporting this bug 🙂 
I hope it's ok that I borrowed your code for the fix.

**Comment by maritz** [comment]
> I hope it's ok that I borrowed your code for the fix.

That's what it was for. ;-)
