### ISSUE TITLE
Exit Code On Failure

### ISSUE THREAD

**Issue by cbautista1002** [maxdome/swagger-combine#67]
Currently if swagger-combine fails to process a file, eg: source swagger files have a syntax error or `apis` listing is invalid, swagger-combine exits with a `0` exit code. Ideally a non-zero exit code should be returned. This would help with automation scripts where we don't want the script to continue processing if swagger-combine wasn't able to process the files.

For now, I'm going to have to check the output of the call to swagger-combine to see if it returned some error text which is not ideal.

Thoughts? Thanks!

**Comment by tmack8001** [comment]
Definitely think this would be helpful.

**Comment by cbautista1002** [comment]
Thanks for taking care of this @tmack8001. Greatly appreciated
